configName: pic32mk_gp_db
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MK1024GPE100
projectName: ''
settings:
  PackageFilter: bsp;core;csp;expresslogic_threadx;micrium_ucos3;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-GP_DFP\1.2.87\atdf\PIC32MK1024GPE100.atdf
